  
name: C/C++ CI

on: 
  workflow_dispatch:

jobs:
  build-esp8266:

    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    strategy:
      matrix:
        package:
          - "WROOM-02"
          - "WROOM-5V2L"
          - "ESP8266_1MB"
          - "WROOM-02-N"
          - "ESP8266_1MB-UNREMAP"
          - "ESP8266_1MB-UNREMAP-NO-TLS-HTTP-ONLY"

    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.0

      - name: clone esp-idf
        run: |
          python -m pip install --user -r requirements.txt
          mkdir build
          echo '{"platform": "PLATFORM_ESP8266", "module": "${{matrix.package}}", "silence": 0}' > build/module_info.json
          ./build.py reconfigure || echo "skip exception"
        shell: bash
      - name: Install dependencies
        env:
          IDF_PATH: ${{ github.workspace }}/esp-idf
        run: |
          python -m pip install --user -r ${{ github.workspace }}/esp-idf/requirements.txt
      - name: Compiling
        run: |
          python ./esp-idf/tools/idf_tools.py --non-interactive install && eval "$(python ./esp-idf/tools/idf_tools.py --non-interactive export)" || exit 1
          python ./esp-idf/tools/idf_tools.py export --prefer-system
          ./build.py build
          upload_dir=esp8266-${{matrix.package}}
          mkdir -p $upload_dir $upload_dir/bootloader $upload_dir/partition_table $upload_dir/customized_partitions $upload_dir/factory
          cp build/flash_project_args $upload_dir/download.config
          cp sdkconfig $upload_dir/
          cp build/*.bin $upload_dir/
          cp build/*.elf $upload_dir/
          cp build/*.map $upload_dir/
          cp build/bootloader/*.bin $upload_dir/bootloader/
          cp build/partition_table/*.bin $upload_dir/partition_table/
          cp build/customized_partitions/*.bin $upload_dir/customized_partitions/
          cp build/flasher_args.json $upload_dir/
          cp build/flash_project_args $upload_dir/download.config
          cp build/factory/* $upload_dir/factory
        shell: bash

      - name: Zip firmware
        run: |
          tar -czvf /tmp/esp8266-${{matrix.package}}.tar.gz esp8266-${{matrix.package}}
        shell: bash

      - name: create release
        uses: softprops/action-gh-release@v2
        id: release
        with:
          name: "build-results"
          draft: true
          files: |
            /tmp/esp8266-${{matrix.package}}.tar.gz

